Task 2
katdunaj/FutureCollars-Java-Katarzyna-Dunaj pull request #2
Opened 2021-09-04 13:42 UTC by katdunaj

2021-09-08 12:12 UTC, radoslawdabrowski approved these changes
I will approve it besides of comments.

2021-09-08 12:12 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/model/Company.java
> +    public Company(final int id, long taxIdentificationNumber, String address) {
could be just lomok's @RequiredArgsConstructor

2021-09-08 12:12 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/model/Invoice.java
> +    public Invoice(UUID id, LocalDateTime date, Company from, Company to, List invoiceEntries) {
could be just lomok's @AllArgsConstructor

2021-09-08 12:12 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/model/InvoiceEntry.java
> +public InvoiceEntry(String description, BigDecimal price, BigDecimal vatvalue, VAT vatrate){
could be just lomok's @AllArgsConstructor

2021-09-08 12:12 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/model/InvoiceEntry.java
> +public InvoiceEntry(String description, BigDecimal price, BigDecimal vatvalue, VAT vatrate){
od @Data

2021-09-08 12:12 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/service/InvoicingService.java
> +@RequiredArgsConstructor
it is nice to separate class code from imports

2021-09-08 12:12 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/service/InvoicingService.java
> +@RequiredArgsConstructor
I mean empty line

2021-09-08 17:41 UTC, michalflis commented on app/src/main/java/pl/futurecollars/invoicing/db/InMemoryDatabase.java
> +        return Optional.empty();
Why are you returning empty Optional instead of updatedInvoice?

2021-09-08 17:41 UTC, michalflis commented on app/src/main/java/pl/futurecollars/invoicing/model/VAT.java
> +    Vat(double rate) {
Is it float or double?

2021-09-08 17:41 UTC, michalflis commented on app/src/main/java/pl/futurecollars/invoicing/service/InvoicingService.java
> +
This one empty line is sting my eyes :)

2021-09-09 08:41 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/service/InvoicingService.java
> +
It is actually pretty normal construction :) you need to get used to repeated methods, when comes to code abstraction.

2021-09-09 08:41 UTC, radoslawdabrowski commented on app/src/main/java/pl/futurecollars/invoicing/model/VAT.java
> +    Vat(double rate) {
both are good

2021-09-09 08:42 UTC, radoslawdabrowski requested changes
Fix updateInvoice method

2021-09-09 18:16 UTC, radoslawdabrowski approved these changes

2021-09-09 20:19 UTC, michalflis approved these changes

2021-09-15 15:52 UTC, merged